# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7s50csga324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/swath/bcd_7seg/bcd_7seg.cache/wt [current_project]
set_property parent.project_path C:/Users/swath/bcd_7seg/bcd_7seg.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/swath/bcd_7seg/bcd_7seg.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/swath/binary_bcd_9bits/binary_bcd_9bits.srcs/sources_1/new/binary_bcd_9bits.v
  C:/Users/swath/bcd_7seg/bcd_7seg.srcs/sources_1/new/bcd_7seg.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/swath/bcd_7seg/bcd_7seg.srcs/constrs_1/new/bcd_7seg.xdc
set_property used_in_implementation false [get_files C:/Users/swath/bcd_7seg/bcd_7seg.srcs/constrs_1/new/bcd_7seg.xdc]


synth_design -top bcd_7seg -part xc7s50csga324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef bcd_7seg.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file bcd_7seg_utilization_synth.rpt -pb bcd_7seg_utilization_synth.pb"
